require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.onedark"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsights"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.icons"
vim.cmd "colorscheme onedark"
